# Generated by Django 5.2.17 on 2026-09-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=4)),
                ('currency_code', models.CharField(max_length=3)),
                ('min_price', models.BigIntegerField()),
                ('max_price', models.BigIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='locations.country')),
            ],
            options={
                'unique_together': {('country', 'listing_type')},
            },
        ),
    ]
